env:
  # For default users
  # cache_root: "cache"
  # For internal use with persistent storage
  # cache_root: "/export/home/.cache/minigpt4"
  # cache_root: "/home/sist/zyang/.cache/minigpt4"
  cache_root: "/data/zyang/.cache/minigpt4"
